### ISSUE TITLE
Why not to use node-sass as a dependency rather than a peerDependency?

### ISSUE THREAD

**Issue by wizardzloy** [jtangelder/sass-loader#122]
I am asking this because as you probably already know starting from npm@3.x `peerDependencies` won't be automatically installed. This will force user of the `sass-loader` to explicitly mention `node-sass` in her dependencies/devDependencies. Do we somehow benefit from using `node-sass` as a `peerDependency`?

**Comment by Aluxian** [comment]
From the README:

> Starting with 1.0.0, the sass-loader requires node-sass as peerDependency. Thus you are able to specify the required version accurately.

This is so that you can choose what version of `node-sass` to use yourself.

**Comment by jhnns** [comment]
I've followed these discussions in several repositories.

I think it's a huge benefit for all these "plugin modules" like the sass-loader if you can specify the exact Sass/LESS/grunt/gulp/whatever version. These "plugin modules" are just a thin layer between your app and another big library. It does not feel right if they bring this dependency in. And it's very time-consuming to handle all the "bump version" PRs :)

I'm open for further discussion, but we won't change this soon. That's why I'll close this for now.
