### ISSUE TITLE
Support for globbed imports?

### ISSUE THREAD

**Issue by Lordnibbler** [jtangelder/sass-loader#151]
Maybe this is just unclear in the instructions, but it seems that `sass-loader` does not support globbed imports, like `@import “pages/**/*”? i keep seeing the error:

```
22:33:06 hot.1    | Module build failed:
22:33:06 hot.1    | @import "../refills/**/*";
22:33:06 hot.1    |        ^
22:33:06 hot.1    |       File to import not found or unreadable: ../refills/**/*/Users/nibbler/Code/github/railsblog/app/assets/stylesheets/base/
```

**Comment by Lordnibbler** [comment]
Ah, after a little more digging I found this: https://github.com/Aintaer/import-glob-loader

Seems to work nicely, but wasn't immediately obvious to me that Rails normally handled the sass import globbing for me.

**Comment by jezstephens** [comment]
import-glob-loader seems to have a couple of drawbacks.

- It screws up the line numbers in Webpack's error messages by inserting additional lines into the input.
- When used with no file extension it includes all files, so if you have Sass files mixed with other non-CSS files it's necessary to say `foo/**/*.scss`. This could be argued as a good thing, but I think it'd be more intuitive if `foo/**/*` was equivalent to `foo/**/*.scss`.

So perhaps sass-loader could support Sass-specific globbing a bit better than import-glob-loader.

I found that "../foo/**/*" worked with import-glob-loader, by the way.

**Comment by jhnns** [comment]
@jezstephens 

> It screws up the line numbers in Webpack's error messages by inserting additional lines into the input.

This should be reported to the import-glob-loader

> When used with no file extension it includes all files, so if you have Sass files mixed with other non-CSS files it's necessary to say foo/**/*.scss. This could be argued as a good thing, but I think it'd be more intuitive if foo/**/* was equivalent to foo/**/*.scss

Yes, I think, it is a good thing to add the file extension explicitly.

> So perhaps sass-loader could support Sass-specific globbing a bit better than import-glob-loader.

I think the import-glob-loader is doing a pretty decent job here. I don't want to add this feature to the sass-loader because the import mechanism is [already pretty complicated](https://github.com/jtangelder/sass-loader/blob/a6cc46f3176499c013ee0d5b565f5392f338a8d9/index.js#L308-L363). Once we started to implement it here, we are responsible to maintain that feature.
