### ISSUE TITLE
Extract SCSS

### ISSUE THREAD

**Issue by tuvistavie** [jtangelder/sass-loader#205]
Hi,

I know that we can use the `ExtractTextPlugin` to extract the CSS to a different file,
however, would there be anyway to extract the uncompiled SCSS to another file?

I am using SCSS variables to change the theme in my application, and having to
compile with webpack takes much longer than a simple SASS compilation would,
so I was wondering if there would be a way to simply extract it.

Thanks.

**Comment by mkoryak** [comment]
a simple sass compilation will not transform your css image urls into the ones that webpack transformed and extracted. you still need to use webpack. 

if you are still having this problem, i can help you - i have done exactly this.

**Comment by tuvistavie** [comment]
@mkoryak Sorry for the late answer.
I am still looking for a solution, so I would be really glad if you could help me, thank you very much!

**Comment by jhnns** [comment]
Sorry, for me it's not clear what you are trying to achieve... why should the sass-loader also output sass code?

**Comment by ivebencrazy** [comment]
Heyhey I know this is old-ish, but I was just playing with this recently, thought I should chime in, to help anyone else that runs into this issue.

I ran into this problem while making a library, where I wanted a user to be able to import either the .css file OR the .scss file (in case the user wants to use my mixins, etc).  So I think what @tuvistavie  was looking to do is have a resulting .js file, .css file, and .scss file as his output.

 I think @tuvistavie is just using the wrong tool for the job.  What he really wants is something that will just follow the imports and append everything together without touching anything else.  I use [postcss](https://github.com/postcss/postcss) and [postcss-loader](https://github.com/postcss/postcss-loader) with the [postcss-scss](https://github.com/postcss/postcss-scss) plugin, so that it can handle the scss. I then extract this separately. This has all my sass variables and things intact.

I didn't really want to build a loader, and I stumbled upon this slightly hacky solution, so I'm just using that (or look at the full code [here](https://github.com/Blanket-Warriors/Zuck.js/blob/master/webpack/webpack.split-source.js)):

**Example:**
```js
var multi = require("multi-loader");
var ExtractTextPlugin = require("extract-text-webpack-plugin");

var cssPlugin  = new ExtractTextPlugin("styles.css",  { allChunks: true });
var scssPlugin = new ExtractTextPlugin("styles.scss", { allChunks: true });

var cssLoader  = cssPlugin.extract("style",  [ "css", "postcss", "sass" ]);
var scssLoader = scssPlugin.extract("style", [ "css", "postcss" ]);

module.exports = {

  ...

  module: {
    loaders: [
      {
        test: /\.(css|scss)$/,
        loader: multi(cssLoader, scssLoader) // Use both loaders at the same time
      }
    ]
  },
  plugins: [ cssPlugin, scssPlugin ],
  postcss: () => []
}
```

**Dependencies:**
```js
"css-loader": "^0.25.*",
"extract-text-webpack-plugin": "^1.0.1",
"multi-loader": "^0.1.0",
"node-sass": "^3.10.1",
"postcss": "^5.2.5",
"postcss-loader": "^1.0.0",
"postcss-scss": "^0.3.1",
"sass-loader": "^4.0.2",
"style-loader": "^0.13.1",
"webpack": "^1.13.2",
```

I guess it seems like a lot of things to get this to work, but I was already using postcss, so worked for me.  Hope it helps!

**Comment by jhnns** [comment]
I think, the [multi-loader](https://www.npmjs.com/package/multi-loader) was the missing piece :)

**Comment by tuvistavie** [comment]
@ivebencrazy That's exactly what I was looking for, thanks! :smile:

**Comment by delsvr** [comment]
@ivebencrazy Are you able to get your particular example (i.e. multi-loader with ExtractTextPlugin) working in webpack 2/3? With your example, all of the initial loaders process the import (sass, css), but no file is extracted. If I add style-loader, the styles are just put into `<style>`, as expected. Any ideas?

**Comment by ivebencrazy** [comment]
@delsvr  Sorrysorry, when I moved this project to webpack 2 was also when I moved away from using Sass, so I don't have a Webpack 2 example.

But no files are extracted at all?  That sounds like maybe the way you're using ExtractTextPlugin isn't working, maybe.  I think I remember the API changing for that sometime between Webpack 1 and Webpack 2, so maybe check the version you're using and if the API for that might have changed.
