### ISSUE TITLE
includePaths not working as expected

### ISSUE THREAD

**Issue by andreicek** [jtangelder/sass-loader#308]
Hi,

I've ran in this issue a couple of times and I can't get it to work. It either works well, or doesn't at all. Consider this - I have a folder structure like this:

```
example/
├── application.js
├── images
│   └── logo.svg
├── styles
│   └── application.scss
└── webpack.config.js
```

I would like for `main.scss` to look like this eg.

```CSS
body {
    background-image: url('images/logo.svg');
}
```

Now, Webpack has a property called `resolve.root` that can take an array of paths where Webpack will try to resolve them. According to the documentation of this loader this will work if I create a `includePaths` property in the Webpack configuration. What I have is this: (I've omitted the loaders and everything not related to this)

```JavaScript
{
  resolve: {
    root: [
      path.join(__dirname, 'images')
    ],
    modulesDirectories: [
      'node_modules'
    ]
  },
  sassLoader: {
    includePaths: [
      path.join(__dirname, 'images')
    ]
  },
  module: {
    loaders: [{
      test: /\.scss$/,
      loader: ExtractTextPlugin.extract('css-loader!sass-loader')
    }]
  }
}
```

And this will not work. The fix we currently use is the following:

```CSS
body {
    background-image: url('../images/logo.svg');
}
```

Is this a configuration issue or something in the loader itself?

Thanks!

**Comment by jhnns** [comment]
`includePaths` is only working for sass imports. `url()` statements are left untouched by the sass-loader. The css-loader will try to resolve `url()` statements, and a statement like `url('images/logo.svg');` will be translated to `url('./images/logo.svg');` because the CSS syntax does not distinguish between module imports and relative imports.

If you really want this behavior, you need to write `url('/images/logo.svg');` and use the `root` option of the css-loader like this:

```
 module: {
    loaders: [{
      test: /\.scss$/,
      loader: ExtractTextPlugin.extract([
        'css-loader?' + JSON.stringify({
          root: path.join(__dirname, 'images')
         }),
        'sass-loader'].join('!'))
    }]
  }
```

However, I don't really recommend this because it defeats the purpose of using webpack for stylesheets. If you need to build it this way, maybe it's not a good idea to use webpack for the stylesheets.
