### ISSUE TITLE
Ignore url()s import?

### ISSUE THREAD

**Issue by datpham23** [jtangelder/sass-loader#46]
Is there a way I can tell sass-loader to ignore urls() states so that it doesn't try to import them?

@font-face {
  font-family:'Myriad Set Pro';
  font-style:normal;
  font-weight:100;
  src:url("../fonts/MYRIADPRO-REGULAR.OTF") format("OTF"), url("/resources/fonts/MYRIADPRO-REGULAR.OTF") format("truetype");
  *src:url('');
}

ERROR in ./resources/fonts/MYRIADPRO-REGULAR.OTF
Module parse failed: /~/Developer/Project/resources/fonts/MYRIADPRO-REGULAR.OTF Line 1: Unexpected token ILLEGAL

**Comment by jhnns** [comment]
Afaik libsass doesn't touch urls(). This error is probably caused by the css-loader. 

The webpack-way of doing this is to configure the [file-loader](https://github.com/webpack/file-loader) or [url-loader](https://github.com/webpack/url-loader) for these binary files.

If you're really sure that webpack shouldn't manage these assets, you can use [root urls](https://github.com/webpack/css-loader#root-relative-urls) (= urls starting with a `/`) to signalize the css-loader, that it shouldn't touch them.
