### ISSUE TITLE
Getting contents without loading

### ISSUE THREAD

**Issue by nwhite89** [jtangelder/sass-loader#55]
I'm wanting to be able to get the contents within JS I can use ``css-loader`` I know and that passes me back an array with a nested array which doesn't feel very nice as a small change could quite easily break that.

Can you think of anything to be able to get the contents straight away because I am wanting to do my own loading without having to use ``style-loader``?

**Comment by jhnns** [comment]
The `sass-loader` just [returns a string containing css](https://github.com/jtangelder/sass-loader/blob/master/index.js#L43) so you should be free to do whatever you want. However, I do recommend that you use the css-loader, so that all referenced images are written to the output folder as well.

I don't know anything about the css-loader returning arrays or something. I thought it would also just return a string (but I also haven't used the output directly yet).

**Comment by nwhite89** [comment]
Yeah I think I will need to use ``css-loader`` come to think of it because of images etc. however, css-loader does do an array but I will take a look at ``css-loader`` when it comes to it thanks (feel free to close if you wish) thanks @jhnns
