### ISSUE TITLE
Single line comments throw error

### ISSUE THREAD

**Issue by fabyeah** [jtangelder/sass-loader#74]
Block comments /* */ are fine, but 
// single line comments inside a style block will produce an error.

I frequently use these to quickly test something and then possibly revert to the old state.
So it would be nice if those are supported.

**Comment by jhnns** [comment]
I don't think that this is a sass-loader issue, because we're just passing the input to [node-sass](https://github.com/sass/node-sass) which passes it on to [libsass](https://github.com/sass/libsass). 

You could make a PR to [sass-spec](https://github.com/sass/sass-spec) to demonstrate the problem. Maybe @mgreter can help you.

**Comment by fabyeah** [comment]
Weird. In another project, I use grunt-sass without a problem, and that also uses node-sass/lib-sass...??

**Comment by richard-lopes** [comment]
@fabyeah Are you using `ccswring` by any chance ? We got the same issue. Removing it from postcss solved the problem for us.
