### ISSUE TITLE
node-sass in peerDeps

### ISSUE THREAD

**Issue by matmuchrapna** [jtangelder/sass-loader#82]
Why do we need peerDeps? I’m not trolling or smth, but I don’t understand, can you help me?

**Comment by jhnns** [comment]
No problem, that's a legitimate question :grin: 

We had the experience that most of the time it's more useful when the app author is able to specify the exact module version. sass-loader is basically just calling `render()`, the actual language features are used by you, the app author.

Otherwise we had to publish a new version for each `node-sass` version, which is a maintenance nightmare.

It's the same problem with the less-loader btw.

**Comment by matmuchrapna** [comment]
Thanks, got it
