### ISSUE TITLE
SVG background-image

### ISSUE THREAD

**Issue by henriquea** [jtangelder/sass-loader#84]
@jhnns I'm trying to do a simple:

```sass
.Icon {
  background-image: url(!file!../../assets/icon-forward.svg);
}
```

This is how my module looks like:

```javascript
module: {
  loaders: [{ 
    test: /\.js$/, 
    loaders: ['jsx-loader'], 
    exclude: '/node_modules/' 
  },
  { 
    test: /\.svg$/, 
    loader: 'file-loader' 
  },
  {
    test: /\.scss$/,
    loader: 'style!css!sass'
  }]
}
```

I'm getting `Cannot find module "./!file!../../assets/icon-forward.svg"`. What am I missing here?

Cheers

**Comment by rixrix** [comment]
Hi

Since you have file loader defined in Webpack config, then might as well change the following line from

`background-image: url(!file!../../assets/icon-forward.svg);`

to

`background-image: url(../../assets/icon-forward.svg);`

cheers

**Comment by henriquea** [comment]
@rixrix duh! I haven't tried it and of course it does work. I'm closing this now, thanks!

**Comment by rixrix** [comment]
@henriquea happy to help, you're welcome!

**Comment by LiquidMusic1** [comment]
I am having the same (similar) issue and used the same process to get webpack to transpile.  However, when i load the site, I am seeing: `list-style-image: url([object Module]);` instead of the file.  A new file was created that looks like `b8167724b8f6274ebc15b40e9fec05fd.svg`.  and of course, the file is not rendering on the page.  What additional information can I provide to help?  I'm a webpack novice.

**Comment by evilebottnawi** [comment]
@LiquidMusic1 update all loaders to latest version

**Comment by LiquidMusic1** [comment]
@evilebottnawi in my package.json file it has each one of the loaders listed with the caret as `{package}:^{version#}`  that should give me the most recent version of those packages right?

**Comment by evilebottnawi** [comment]
@LiquidMusic1 run `npm outdate`
